#******************************************************************************
#   Makefile
#
#   Part of the template for ThiefLib script modules
#   Copyright (C) 2012-2013 Kevin Daughtridge <kevin@kdau.com>
#   Adapted in part from Public Scripts
#   Copyright (C) 2005-2013 Tom N Harris <telliamed@whoopdedo.org>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#******************************************************************************

# CUSTOMIZE to the short name of your module.
MODULE_NAME = SampleModule

# CUSTOMIZE to the platform you are building from (Windows is i686-w64-mingw32).
HOST = x86_64-linux-gnu

# This should not change; it is the Dark Engine's platform.
TARGET = i686-w64-mingw32

# CUSTOMIZE to the location of the ThiefLib headers and archives.
THIEFLIBDIR = ../

# CUSTOMIZE to list your scripts' headers.
SCRIPT_HEADERS = \
	SampleScript.hh

include $(THIEFLIBDIR)/module.mk

